### ISSUE TITLE
Mailing list

### ISSUE THREAD

**Issue by voxadam** [owntracks/owntracks#1]
A mailing list for the project would be useful. It would be nice to have a place, a forum even, to chat about OwnTracks and location awareness in general.

**Comment by jpmens** [comment]
Apologies for leaving this unanswered for such a long time. We've been considering this and have decided that Google Groups is not what we want. Your idea is very good, however, and we're working on getting something set up which will please us (and integrate well into our small team) and be flexible/powerful for our users. Forums are a no-go; same for Facebook et.al. 

Would you kindly do us a favor and kill that group so we don't have a dangling forum called "owntracks" which isn't going to be used or monitored by us? Greatly appreciated, and we'll get back here as soon as we have a solution (which won't be long now).

Thanks again.

**Comment by jpmens** [comment]
I think we're almost ready to rumble. Join us at [https://community.owntracks.org](https://community.owntracks.org).

**Comment by voxadam** [comment]
Done.

**Comment by jpmens** [comment]
Thank you @voxadam
