### ISSUE TITLE
openhap not reporting non-location updates when using mqtt protocol

### ISSUE THREAD

**Issue by maxfieb** [owntracks/owntracks#10]
The non-location updates dont appear to be updating or are going somewhere else than the configured owntracks/<user>/<identifier> when using mqtt transport. I am only seeing type=location updates on ios when using mqqt protocol. Of the non-location updates, i have tries the "Publish Settings" and "Publish Waypoints" they do not appear at all when mqtt is configured as the transport.

BUT. If i configure a simple http endpoint, that takes the JSON as a http(s) POST, then re-publish that data as JSON into mosquitto using a php mqtt client, i see location types, and "Publish Settings" and "Publish Waypoints" types. [edit it does, it puts them under owntracks/user/deviceid/dump and owntracks/user/deviceid/waypoints ]

I have not seen any geofencing requests, but that is mostly because my regions are thrown away every time i switch between http and mqqt. The only difference here is that i am publising the JSON under a single topic (mostly as it is just for testing) but http seems far more reliable than mqqt which randomly stops sending updates until the connection is goosed - usually my retyping the password field)

Are all the non-location mqtt updates sent to the configured topic, or do they go somewhere else ?

And can the regions only be cleared when you switch from public, to a non-public transport, it seems pretty silly to clear them when changing http to mqtt as they are both potentially private types.

Contrasting between running http and mqtt, http seems a lot more reliable, mqtt seems to randomly lose connection, and never retry it. If you lose signal for a while, it doesn't retry the connection reliably.

So by itself, http is more reliable, as it makes a new connection for every location update. The mqtt does not seem to do this, it assumes the connection will always be present. For a mobile app, this seems rather odd.

I am using owntracks 9.1.6 on ios. mosquitto version 1.3.4 (raspberry pi) with tls and authentication configured

**Comment by jpmens** [comment]
I don't really see what your issue is about ...

1. MQTT is very reliable (we use it permanently on a number of devices), and reconnection on iOS works well.
2. All topics are published, as well as waypoints and configuration to the broker. I can only assume you have (incorrect?) ACLs set up which forbid you seeing them.
3. Mass clear of regions is done when switching modes because we defined it that way.
4. HTTP mode is just "different"; it would be wrong to term it more reliable.
5. Your Mosquitto version is **ancient** and is probably why you're having problems.

**Comment by maxfieb** [comment]
i'll try a newer version of mosquitto.. it might be nice to have a tooltip that the publish settings / waypoint topics are owntracks/user/deviceid/dump and owntracks/user/deviceid/waypoints, probably i got an old disrto version. i'll try h t t p : //jpmens.net/2013/09/01/installing-mosquitto-on-a-raspberry-pi/  :)

**Comment by maxfieb** [comment]
1.3.4 was the newest available for raspberry pi, from the default repository, but the repository references in the previous comment is much better, it has the current release version. and it does seem much more stable, although to be fair even to the old version, many issues were my own.

a noob trap i suppose. dont use the default repository always.. esp for mosquitto, at the very least the features of the new version offer a much richer selection. 

a useful debugging tools to see all activity was : mosquitto_sub -t owntracks/#

the guide at : http://owntracks.org/booklet/guide was also very helpful, once i found it.

sorry for the spam. may your day be a good one
