### ISSUE TITLE
Enhancement Request: WiFi / SSID based region geofences

### ISSUE THREAD

**Issue by tylerstraub** [owntracks/owntracks#11]
Greetings OwnTracks team,

I've been using OwnTracks as our primary solution for detecting presence and performing zone based automation within the home-assistant.io platform. 

Originally, I started out using a combination of OwnTracks and NMAP scans of the local Wi-Fi so that home presence would be detected even if the GPS based mechanism failed. 

This started to become a problem when I discovered how different mobile devices deal with being pinged and how network traffic is often queued or blocked according to its assigned class or to conserve battery life. 

Since then I have reverted to an entirely GPS based method but it occurred to me that OwnTracks could potentially support zone entering and leaving based on the connection or proximity to a WiFi network much like how support for iBeacons are provided to this day.

Is this something that would be considered of value to implement? 

Cheers!

**Comment by jpmens** [comment]
Thanks for your suggestion, but: we have discussed this (and, IIRC, even done a sample implementation for Android), but it didn't work reliably. I vaguely recall that it's not possible at all on iOS, and on Android something else went wrong.

If I'm incorrect, either @ckrey or @binarybucks will surely chip in to tell me off. :-)

**Comment by jpmens** [comment]
Here's the nitty gritty: [Not working <= Android 6, not possible with Android 7](https://github.com/owntracks/android/issues/157).

Closing this for now.

**Comment by tylerstraub** [comment]
I figured it may have may have been something like this. It feels like a natural progression of the region feature but it's a bummer that current API doesn't allow things to go smoothly. Thank you for your time!
