### ISSUE TITLE
[Androind app, private mqtt] Question: Connection through Tor 

### ISSUE THREAD

**Issue by wolass** [owntracks/owntracks#12]
Hi,

I want to connect Owntracks to my private MQTT broker through Tor Hidden Service. 
I am using an android device with Orbot installed and VPN-ed Owntracks to connect through Tor. 
As the 'private MQTT' host I am using the .onion address provided by Tor. The torrc configuration file is also configured adequately = service with a correct password was added.

But I am having problems connecting. The error I'm getting is "Host is unresolved". 

I also tried to configure this through 'private HTTP' but I get 'incomplete configuration' info from owntracks. (I'm not providing any CA cert. is that it? )

I think when connecting through Tor the CA cert is redundant.

I also could not find any 'sucessful' sep-by-steps of people connecting through Tor. 

Any help with this?

**Comment by jpmens** [comment]
This is not an Android bug, so I'm closing now.
Please post your question on our [Community Site](https://community.owntracks.org)
