### ISSUE TITLE
Owntracks and Orbot

### ISSUE THREAD

**Issue by dbenhart** [owntracks/owntracks#13]
I am using the newest versions of the Owntracks and Orbot apps to send data to a private MQTT broker. The broker is exposed as a TOR Hidden Service and ties into my Home Assistant setup. I know that Owntracks works, at least some of the time, because if I'm at home and change the host IP from the .onion address to the server's IP address, it connects and updates correctly. I know that Orbot works because I also have the web front end for Home Assistant exposed as a Hidden Service and I can connect to that via Orfox. The problem is that when I change the MQTT Broker host to the .onion address, Owntracks enters a state where it is always connecting, but never connects. I have Orbot set to run Owntracks through its "app-VPN", which I've been told will allow it to resolve a .onion address. I'm not sure which component is causing a problem, so I'm checking with all parties.

**Comment by jpmens** [comment]
You've confirmed OwnTracks works when you direct it to your broker. We're not familiar with the other components so we cannot really help. If you think it's one of our apps which has a bug, please open an issue for the corresponding OS (iOS/Android), thanks.
