### ISSUE TITLE
Consider a 'checkin' message schema

### ISSUE THREAD

**Issue by CloCkWeRX** [owntracks/owntracks#14]
As a user, I want to sometimes share my exact location (a point of interest).

Lat/Lon may not be accurate enough for multiple level buildings, or large indoor spaces (a mall)

If I could publish from my Owntracks client:
- location_url - A website or Openstreetmap location refered to by url
- location.primary_title
- msg/checkin.description
- start/end date (optional) - maybe already covered by tst attribute
 - additional_urls[] - other identifiers, like wikidata or similar

I chose location_href as a generic URL, but would imagine popular data sources could include things like an Openstreetmap API lookup for a POI, or similar from a Google geocoding result.

The initial use case is 'share location more precisely', but it would enable things like:
- Determine likely opening hours for a business
- Show interesting information about your current location
Etc

**Comment by CloCkWeRX** [comment]
An alternative to this may also be to enhance 'waypoint' behaviour in the clients to make it a lot easier to add these and broadcast 'enter' events

**Comment by CloCkWeRX** [comment]
More context: https://www.openstreetmap.org/user/CloCkWeRX/diary/39928 (perhaps these are better as a fork of osmabd/owntracks mixed together, but would love to hear your thoughts on an open and extensible way to do some of these things)

**Comment by jpmens** [comment]
We won't be doing this.
