### ISSUE TITLE
Last verion (1.1.5) for Android doesn't update location

### ISSUE THREAD

**Issue by dib0** [owntracks/owntracks#16]
Hi!

Your app is great, but the last version (1.1.5) for Android doesn't update the location anymore. If I restart my device the location will update, but after that n update is processed by the application (other apps do get location updates).

If I open Owntracks I se the map with the right current location, by the pointer with my own device doesn't show on that location (just on the first one).

The report date/time also doesn't udpate.

I'm on an Android 5.1 device. The previous version worked without any problem. I hope you can fix this. If you need any more information or I can help you test something, please let me know.

**Comment by binarybucks** [comment]
Please reopen this issue at https://github.com/owntracks/android/issues.
