### ISSUE TITLE
Android contacts are not showing.

### ISSUE THREAD

**Issue by DanOBrien** [owntracks/owntracks#2]
I've created a contact with the custom IM title of owntracks and the IM name of owntracks/Name/Device, but the contact never shows in the app. What am I doing wrong?

**Comment by DanOBrien** [comment]
It just worked on an LG V410 tablet, my cell phone, Galaxy S5, doesn't seem to work and both devices have the same contacts synched. Weird...

**Comment by jpmens** [comment]
If you wish to report issues with our Android app, we'd appreciate you doing to at [https://github.com/owntracks/android/issues](https://github.com/owntracks/android/issues), thanks.
