### ISSUE TITLE
Sending data to TRACCAR

### ISSUE THREAD

**Issue by howardweng** [owntracks/owntracks#23]
I am sending the data to TRACCAR using http. 
Can anyone help me for the Owntracks setting? I always has reporting error. I do know where went wrong.

I followed the instruction as following. 
https://owntracks.org/booklet/features/traccar/ 

[setting image](https://www.dropbox.com/s/q26l8m3hcd0dzqe/S__12206126.jpg "setting")
[status image](https://www.dropbox.com/s/0bg3oqmgazn3oqz/S__12206127.jpg "status")
Please click to view images, sorry, I do not know to display immediately.

**Comment by jpmens** [comment]
You are getting HTTP code 400 Bad Request sent to you from traccar. Please check the logs there to determine what the problem is. Traccar doesn't "like" the data you're giving it, but we cannot tell from that code why that is. Possibly because you haven't yet created the device

**Comment by howardweng** [comment]
Thanks JPMens, that is correct , also for your hint. 
2018-06-13 10:07:01  WARN: Unknown device - owntracks/howard/iPhone1 (223.136.39.114)
After adding this in and it works perfectly.

**Comment by jpmens** [comment]
Glad to hear.
