### ISSUE TITLE
How to remove friends who no longer use the service?

### ISSUE THREAD

**Issue by begleysm** [owntracks/owntracks#25]
Hello,

I run a private MQTT server for OwnTracks.  My wife and I are both on it and are happy (Android).  I put my parents on it too but they both had problems with battery drain and removed the app (Android).

They've been off the server for months but they still show up in my friends list and their icons still appear at there last known location months ago.

How can I remove them?

Furthermore, is there a setting/feature that allows the auto-removal of clients who haven't checked-in in, say, a month?

**Comment by jpmens** [comment]
As to your first question: publish a null retained payload to the topic:

```
mosquitto_pub -t topic -r -n
```

as to your second question: no, there is no such feature.

**Comment by raphaelg** [comment]
Unfortunately,  friends lists are not correctly purged in IOS app, but it works very well on Android.

**Comment by jpmens** [comment]
You swipe the friend out. Does this not work for you?

**Comment by raphaelg** [comment]
> You swipe the friend out. Does this not work for you?
> […](#)
> On 14. Sep 2020, at 11:58, raphaelg ***@***.***> wrote: ﻿ Unfortunately, friends lists are not correctly purged in IOS app, but it works very well on Android. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

My bad. Deleted on the mqtt server without swaping on IOS in Friends list. Works now. Thanks !
