### ISSUE TITLE
Always the same coordinates...

### ISSUE THREAD

**Issue by AlainDamme** [owntracks/owntracks#26]
Hi
Just started using the iOS app, scenario HTTP. I am receiving the data through the Node Red node on my Raspberrypi Pi. Only problem is I keep getting the same lat/lon. On my Phone the correct location is shown on the map, lat/lon is correct. But when I publish the wrong coordinates arrive on my Pi... maybe relevant these are the coordinates where I installed the app...

Any help would be greatly appreciated.

**Comment by jpmens** [comment]
Recommendation: check your node-red configuration; it’s highly unlikely you’ll get same data when publishing from our app unless you don’t move. Even then: check the value of tst which indicates the epoch time of publishing.

**Comment by AlainDamme** [comment]
> Recommendation: check your node-red configuration; it’s highly unlikely you’ll get same data when publishing from our app unless you don’t move. Even then: check the value of tst which indicates the epoch time of publishing.

Thanks for your input.
tst corresponds to the time the post was sent, within a few minutes.
I tried sending my own HTTP Post with test data and this was received correctly by Node Red.
So I think the problem is with the app.... However i didnt change the default settings,only selected HTTP and added the url....

**Comment by jpmens** [comment]
If you see the tst JSON element it appears to be a sane payload. 

It would help if you could show us the full JSON your node-red is receiving. Feel free to obfuscate lat/lon for privacy.

**Comment by AlainDamme** [comment]
[log.txt](https://github.com/owntracks/owntracks/files/3760882/log.txt)

Goodmorning

Please see attached file with JSON, a test I did this morning.
I moved more than 7 km between the first and last entry, on my phone I see the correct position on the map. I have just noticed that tst is also always the same…

**Comment by ckrey** [comment]
Which monitoring mode did you select? 
Only Move and Significant mode will track you automatically.
If you are using iOS 13, you  will have to go to Settings/Privacy/Location and give OwnTracks always access to Location

All your locations published in the log.txt file were done manually ("t":"u") and in WiFI environment ("conn":"w")

**Comment by AlainDamme** [comment]
Settings in iOs are ok.
Monitoring mode is Significant.
It seems I’m getting the same Json everytime...

**Comment by AlainDamme** [comment]
This morning I changed modes from HTTP to MQTT and back.
My first location was spot on...I thought it would be OK.
I Log2.txt you will see now I'm getting the same initial location over and over.
While I was moving all morning and location (blue dot) and ED where shown correctly on the map...
[log2.txt](https://github.com/owntracks/owntracks/files/3767390/log2.txt)

**Comment by AlainDamme** [comment]
Installes the app on my iPad and went on the road...
Same problem...maybe an isuue with iOS13 or the app ?
[log3.txt](https://github.com/owntracks/owntracks/files/3767866/log3.txt)

**Comment by ckrey** [comment]
You are using HTTP? If so, make sure your server responds with HTTP Response code 2xx. Otherwise the app will retry to send the same message again and again!

If you are building your own backend, please know what you are doing.

We suggest to use MQTT!

**Comment by AlainDamme** [comment]
I tested the HTTP server and all POSTed data was received without errors.
I will test MQTT, but need to learn more about it first, taking it step by step...

**Comment by ckrey** [comment]
Even if the server receives the POSTed data without errors it has the client about it (by returning 200):
https://owntracks.org/booklet/tech/http/

**Comment by AlainDamme** [comment]
Thank you so much for your patience... I still have so much to learn. I added a HTTP response node and the data came pouring in.
