### ISSUE TITLE
Payload  Encryption Question

### ISSUE THREAD

**Issue by strunker** [owntracks/owntracks#32]
https://github.com/owntracks/owntracks/issues/7

Hello,

Payload encryption is discussed in the above. I have my own flask server that I want to use as the http receiving endpoint for owntracks. It looks like the libsodium equivalent on Python is pynacl. I cant, for the life of me, figure out how to decrypt the payload. I can see the data, and extract it as encrypted data on my web server, but from there I am a bit lost. 

Has anyone ever attempted to decode the payload data outside of the recorder? I am on windows, and there is no easy way to get the recorder working on windows. If anyone has any guidance on how to take the secret from the app and use it to decode the encrypted payload in Python that would be great. 

Ty

**Comment by jpmens** [comment]
It never occurred to me that somebody would want to decode the payload outside of the OwnTracks "ecosystem" and, no, I have never attempted to do so.

Before you continue, I would like to suggest you do not use payload encryption. We implemented it at the time as "something we could do", but there's never been any real need to do so: whether you transport OwnTracks payloads from our apps to the backends via MQTT or HTTP, both can be transport-encrypted with TLS, and that ought to be more than enough.

Be that as it may, if you do manage to decrypt with Python, I'd be interested in how you did it.

Regarding Windows: it _might_ be possible to run the recorder in WSL2. Have you tried that?

**Comment by ganlbarone** [comment]
I 100% understand what you are saying. So, this project I run is exclusively used by me. Its a flask server that I run which hosts a flask/websocket app which I use to control things within my home over an Alexa skill / Samsung watch app. I wrote it, and its only consumed by me.

I do use TLS but with a self signed cert because I just really care about encryption over the internet, not really authenticity for my own little personal project. I have hashed authkeys that are only valid for one minute, then never again, that are inside the encrypted payload, so even if it were to be every cracked somehow it wouldn't necessarily matter. I don't believe the mobile app supports ignoring cert warnings, which is why I was going to just encrypt the payload, transfer it to a normal http endpoint, then pipe over the location data to the flask code process. 

All I wanted to do here is just track my own personal location, and make my code aware of where I am so it can monitor me for a variety of reasons. I installed wsl2 on my server last night and I was going to try the Docker route. However, it just seems needlessly complex for my ultimate goal, and just for a personal project. I would have to run docker, some type of web server, likely NGINX or I guess i could have my Flask code send over a request to the recorder, and then rproxy the traffic over to the recorder. It just seems like a lot to go through, was hoping for just a simple solution that is secure enough for personal use, which then led me to payload encryption, which then landed me at the issue above of not being able to properly decrypt. 

MQTT I dont believe supports self signed certs either, and I had a crazy time trying to get paho / mosquitto working with one.

Ill either do one of the below:
1) Gets lets encrypt going and just go the official tls route and deal with the renewals.
2) Figure out how to extract the first 40 bites decryption key from the encrypted payload and decrypt with nacl.
3) Use docker image and try to sort through all that.

Thanks!

**Comment by strunker** [comment]
I 100% understand what you are saying. So, this project I run is exclusively used by me. Its a flask server that I run which hosts a flask/websocket app which I use to control things within my home over an Alexa skill / Samsung watch app. I wrote it, and its only consumed by me.

I do use TLS but with a self signed cert because I just really care about encryption over the internet, not really authenticity for my own little personal project. I have hashed authkeys that are only valid for one minute, then never again, that are inside the encrypted payload, so even if it were to be every cracked somehow it wouldn't necessarily matter. I don't believe the mobile app supports ignoring cert warnings, which is why I was going to just encrypt the payload, transfer it to a normal http endpoint, then pipe over the location data to the flask code process.

All I wanted to do here is just track my own personal location, and make my code aware of where I am so it can monitor me for a variety of reasons. I installed wsl2 on my server last night and I was going to try the Docker route. However, it just seems needlessly complex for my ultimate goal, and just for a personal project. I would have to run docker, some type of web server, likely NGINX or I guess i could have my Flask code send over a request to the recorder, and then rproxy the traffic over to the recorder. It just seems like a lot to go through, was hoping for just a simple solution that is secure enough for personal use, which then led me to payload encryption, which then landed me at the issue above of not being able to properly decrypt.

MQTT I dont believe supports self signed certs either, and I had a crazy time trying to get paho / mosquitto working with one.

Ill either do one of the below:

Gets lets encrypt going and just go the official tls route and deal with the renewals.
Figure out how to extract the first 40 bites decryption key from the encrypted payload and decrypt with nacl.
Use docker image and try to sort through all that.
Thanks!

**Comment by jpmens** [comment]
Thanks for elaborating! Interesting.

FWIW, Mosquitto certainly supported self-signed certs, at least until version 1.6.something. I've not tried recently, but it should still be possible, at least I see no reason why it shouldn't be.

**Comment by jpmens** [comment]
It's your lucky day, @strunker :-)

I thought I'd glance at whether I'd be able to decrypt an OwnTracks payload in Python, and it turns out I did after all do experiments back in 2016 ... 

I mucked about a bit and converted the lot to Python 3 and have just tested with an OwnTracks iOS encrypted payload and it works.

Example encrypted payload with key `s3cr1t`: this is a base64-encoded string as you'd be receiving in the OwnTracks JSON, i.e. something like

```json
{
   "_type" : "encrypted",
   "data" : "vG0sAik3/+1KwrZ4b27yQtfJEVz6g2v0Os+yGIECNm8PnxwTR7ZUlUYRclgku7eP19FeNjJugxhYnF9pvlxDBzUxYg=="
}
```

I then take the base64-encoded payload and run that into the decryptor:

```console
$ echo "vG0sAik3/+1KwrZ4b27yQtfJEVz6g2v0Os+yGIECNm8PnxwTR7ZUlUYRclgku7eP19FeNjJugxhYnF9pvlxDBzUxYg==" | ./dec.py
Hello from C, how are you?
```

Seems to work.

Here's the very minimal code which, I will assume, you can greatly improve upon. If I've commited Python crimes, do say, please!

```python
#!/usr/bin/env python3

import fileinput
import base64
import nacl.secret  # http://pynacl.readthedocs.org/en/latest/secret/

key = b's3cr1t'

box = nacl.secret.SecretBox(key + bytearray(nacl.secret.SecretBox.KEY_SIZE - len(key)))

for line in fileinput.input():
    ciphertext = base64.b64decode(line.rstrip())

    plaintext = box.decrypt(ciphertext) 
    print(plaintext.decode("utf-8"))
```

**Comment by strunker** [comment]
> It's your lucky day, @strunker :-)
> 
> I thought I'd glance at whether I'd be able to decrypt an OwnTracks payload in Python, and it turns out I did after all do experiments back in 2016 ...
> 
> I mucked about a bit and converted the lot to Python 3 and have just tested with an OwnTracks iOS encrypted payload and it works.
> 
> Example encrypted payload with key `s3cr1t`: this is a base64-encoded string as you'd be receiving in the OwnTracks JSON, i.e. something like
> 
> ```json
> {
>    "_type" : "encrypted",
>    "data" : "vG0sAik3/+1KwrZ4b27yQtfJEVz6g2v0Os+yGIECNm8PnxwTR7ZUlUYRclgku7eP19FeNjJugxhYnF9pvlxDBzUxYg=="
> }
> ```
> 
> I then take the base64-encoded payload and run that into the decryptor:
> 
> ```
> $ echo "vG0sAik3/+1KwrZ4b27yQtfJEVz6g2v0Os+yGIECNm8PnxwTR7ZUlUYRclgku7eP19FeNjJugxhYnF9pvlxDBzUxYg==" | ./dec.py
> Hello from C, how are you?
> ```
> 
> Seems to work.
> 
> Here's the very minimal code which, I will assume, you can greatly improve upon. If I've commited Python crimes, do say, please!
> 
> ```python
> #!/usr/bin/env python3
> 
> import fileinput
> import base64
> import nacl.secret  # http://pynacl.readthedocs.org/en/latest/secret/
> 
> key = b's3cr1t'
> 
> box = nacl.secret.SecretBox(key + bytearray(nacl.secret.SecretBox.KEY_SIZE - len(key)))
> 
> for line in fileinput.input():
>     ciphertext = base64.b64decode(line.rstrip())
> 
>     plaintext = box.decrypt(ciphertext) 
>     print(plaintext.decode("utf-8"))
> ```

This is awesome, I will try this out tonight. The code makes good sense. I wasnt visualizing how you were doing the 0 padding but minusing the length of whatever the user chose from the default 32 byte length makes sense.

What I was going to do in lieu of this. My router supports direct integration with LetsEncrypt. So I wouldnt need to purchase a domain, and manage the dns records, or keep things updated, etc..

On the router I setup a port forward to 8083 to my server running a flask app that would parse the incoming location data. My hope was that the router would act like a layer 7 and terminate the https, and then just forward the request on unencrypted to the back end web server. Sadly, it doesnt seem to function this way, instead the router looks to use layer 4 and just sends the request encrypted onwards to the flask server (see image of encrypted data below hitting the web back end).

If I export the .pem files from the router, and add them to the flask code, everything works and I can reach the endpoint in browser with lock symbol and the OwnTracks app is happy. 

The only annoying thing is that now Ill have to manually export this cert from the router every 3 months. Since I dont own the domain, and the router is getting the lets encrypt cert based on a DDNS service subdomain. I cant add in the required dns record to get these certs on my own. So I would/will need to login to the router every 3 months, extract them and copy them down so that https continues to function.

Either that or I need to purchase a domain, where I can control the actual dns records, so I can request my own certs in an automated fashion via certbot or powershell. 

My own ask would be perhaps in the future if OwnTracks had a toggle to "Ignore cert warnings" and just allow the https to go through without verifying that would be nice. I would never argue this should be the default behavior, because it certainly shouldn't. But for little personal projects where all you really care about is encryption over the internet I dont think that legitimate ssl certs should be a hard requirement in order to send data over TLS. Just my opinion and .2 cents.

Thanks again for all your work on this, and for your responses. I am looking forward to getting past this data aspect of things so I can start to write the code that will be consuming this location data.

![image](https://github.com/owntracks/owntracks/assets/6154660/9e81c0a9-94c6-411e-bec1-8a3092b63fbf)

![image](https://github.com/owntracks/owntracks/assets/6154660/89fca838-e660-42f8-9077-d2a88d1dd5c0)

**Comment by jpmens** [comment]
> My own ask would be perhaps in the future if OwnTracks had a toggle to "Ignore cert warnings" and just allow the https to go through that would be nice.

If memory serves, we actually used to have this but then actively removed that function. There doesn't seem to be a point in doing unauthenticated TLS.

That's one of the reasons for payload encryption: do HTTP, encrypt the payload, and be done with it. :)

**Comment by strunker** [comment]
> > My own ask would be perhaps in the future if OwnTracks had a toggle to "Ignore cert warnings" and just allow the https to go through that would be nice.
> 
> If memory serves, we actually used to have this but then actively removed that function. There doesn't seem to be a point in doing unauthenticated TLS.
> 
> That's one of the reasons for payload encryption: do HTTP, encrypt the payload, and be done with it. :)

Makes good sense, I Imagine the use cases for it are limited. Will post back once I try out the payload encryption and let you know where I land with that and close this thread out.

Thanks again!

**Comment by strunker** [comment]
Got impatient, and had a lull in the day, so gave this a quick shot. This 100% does work, the little code snippet you provided above.

I will post some sample code shortly for anyone else who maybe runs into this, and then close this out entirely. Thank you much @jpmens!

**Comment by jpmens** [comment]
> That's one of the reasons for payload encryption: do HTTP, encrypt the payload, and be done with it.

What I should point out even though it's probably obvious, this will not protect credentials used to access the HTTP endpoint. For that TLS is definitely the way to go.

**Comment by strunker** [comment]
> > That's one of the reasons for payload encryption: do HTTP, encrypt the payload, and be done with it.
> 
> What I should point out even though it's probably obvious, this will not protect credentials used to access the HTTP endpoint. For that TLS is definitely the way to go.

For sure I noticed they are just passed over in base64 as expected. Really existing just to stop random ppl from sending posts to the end point, if its discovered from a scan for example.

In the implementation I am writing I check for basic auth, the user agent, and also the _encrypted type. If all three of those are not there we throw up an error because the post would be abnormal at that point. Additionally, if the decryption fails it means the data sent over is/was also not formatted correct which would also throws an error. 

Additionally, I purchased a cheap one dollar domain yest, and got lets encrypt going, and setup an automated task in PowerShell to renew it every 3 months. I stopped being lazy on that front. While I really do only care about the encryption aspect, due to this being a personal project, this experience underscored the need for legitimizing the cert being used and it's obviously best practice so no argument there.

I will post up some code in the next day or two and then close this out so it doesn't linger open. 

Thanks again for the help/guidance.

**Comment by strunker** [comment]
```
#OwnTracks Code
import logging
# logging.basicConfig(level=logging.DEBUG)
from flask import Flask, render_template, request, Response
import base64
import nacl.secret  # http://pynacl.readthedocs.org/en/latest/secret/
import json
# import reverse_geocode
import reverse_geocoder 
from colorama import init
init(autoreset=True)
from colorama import Fore, Back, Style 
import traceback #for traceback error logging

#Vars/Constants
secretEncryptionkey = b'ENTERENCRYPTIONKEY'
box = nacl.secret.SecretBox(secretEncryptionkey + bytearray(nacl.secret.SecretBox.KEY_SIZE - len(secretEncryptionkey)))
username = "ENTERUSERNAME"
password = "ENTERPASSWORD"
userpass = username + ':' + password
encodedCredential = base64.b64encode(userpass.encode()).decode()
app = Flask(__name__)

#Flask app
#Auth OT route is called from the app, data is extracted and then reverse geocoded. 
@app.route("/AuthOT", methods=['POST']) #methods=['GET','POST']
def AuthPageRoutine():
    try:
        #Request data
        requestMethod = request.method          
        #Main Body
        headInfo = request.headers
        bodyData = request.data          
        jsonData = json.loads(bodyData)
        dataType = jsonData["_type"]
        authHeader = headInfo.get("Authorization")
        userAgent = headInfo.get("User-Agent")
        #Check auth / payload
        if dataType == 'encrypted' and "OwnTracks" in userAgent and encodedCredential in authHeader:
            encryptedData = jsonData["data"]
            encryptedData = base64.b64decode(encryptedData.strip())
            decryptedData = box.decrypt(encryptedData) 
            jsonDecryptedData = json.loads(decryptedData)
            if jsonDecryptedData.get("inregions") != None:
                regions = ",".join(jsonDecryptedData.get("inregions"))
                print(regions)
                knownRegion = "In a known region(s): " + regions
            else:
                knownRegion = "In an unkown region."
            print(knownRegion)
            print(decryptedData)
        else:
            raise ValueError("Any of the following may be true: The payload data is not encrypted, the user agent is wrong, or the auth header is incorrect!")
        coordinateTuple = [(jsonDecryptedData["lat"], jsonDecryptedData["lon"])]
        locationDetails = (reverse_geocoder.search(coordinateTuple))[0]
        # print(locationDetails)
        if locationDetails.get("name") != None:
            print("City: {}\nState: {}\nCountry: {}\nRegion: {}".format(locationDetails.get("name"),locationDetails.get("admin1"),locationDetails.get("cc"),knownRegion))
        else:
            raise ValueError("Could not extract city from tuple: {}".format(coordinateTuple))
        return Response(str("Good"),mimetype='text/html',status=200)
    except Exception as E:
        print(Fore.RED + "\nAlert or Error: AuthMeOT Route - " + format(str(E)))
        print(traceback.print_exc())
        return Response(str("".format(str(E))),mimetype='text/html',status=500) 

#Establish default trap. Browsing the root or any other page will trap and log the request.
@app.route('/', defaults={'path': ''},methods=['GET','POST']) #We allow GET and POST here because GET allows us to send a 410 instead of method not supported. Most other endpoints just need Post.
@app.route('/<path:path>')
def catch_all(path):
    requestData = request.method
    headinfo = str(request.headers)
    remoteaddr = str(request.remote_addr)
    print(Fore.RED + "\nAlert - Default Route: " + remoteaddr)
    return Response(str("Internal Server Error"),mimetype='text/html',status=500)

#Start Web Server | Can run this in https or http. To run in http with just payload encryption above remove the ssl_context argument from the below app.run method.
if __name__ == "__main__":
    app.run(debug=False, use_reloader=False,host='0.0.0.0',ssl_context=('ENTER PATH TO SSL CERT', 'ENTER PATH TO SSL KEY'),port=8083, threaded=True)
```

**Comment by strunker** [comment]
For anyone who stumbles on this thread, the above is a good framework for making your own web server and using payload encryption within the app. I also ended up buying a domain and using lets encrypt so I have TLS in addition to the payload encryption. However, you can remove the ssl_context parameter from app.run and the server will run in non https mode with just payload encryption. Thanks @jpmens  for the guidance on this question. Will close this within 24 hours if there are no critiques on the above. Ty
