### ISSUE TITLE
change icon of tracking ID of user who turned off their client. 

### ISSUE THREAD

**Issue by undrwater** [owntracks/owntracks#34]
If the app of a user is not running, it would be informative to know this information, along with last location. 

Perhaps by removing the color of the tracking ID circle, or some other element.

**Comment by jpmens** [comment]
The last reported location is available by default when your device contacts the MQTT broker (or HTTP server), along with the last reported location is the time when that was reported.

It's pretty much impossible for us to determine "not running", as there's no end-to-end connectivity. For instance a user might have set their OwnTracks app to 'quiet' mode: while nothing is reported, they're not offline.

**Comment by undrwater** [comment]
Thank you.
