### ISSUE TITLE
Shorten navigation keywords

### ISSUE THREAD

**Issue by jpmens** [owntracks/owntracks#37]
I note, after merging #36 ghat the width of navigation at bottom of page is very wide (too wide) on my phone. 

Is there CSS magic to fix this or do we need shorter keywords (`s/ocumentation/s/`)

**Comment by jpmens** [comment]
Seen on desktop: maybe just reduce the width of the buttons a bit?

**Comment by ckrey** [comment]
maybe two little `<br>`s will do the trick:
![Bildschirmfoto 2024-12-06 um 11 58 21](https://github.com/user-attachments/assets/4cb9b898-25a2-4be5-9061-1b4822eecf3f)

**Comment by jpmens** [comment]
Not really beautiful,  is it?

**Comment by ckrey** [comment]
Better if buttons don't have fixed size?
![Bildschirmfoto 2024-12-07 um 09 42 40](https://github.com/user-attachments/assets/b5b14e7c-9b95-4755-bea2-2d51c2140b54)

**Comment by jpmens** [comment]
IMO much better. Possibly even more so if we `s/documentation/docs/` ?
I don't know how to shorten `mastodon`, unless we use `Fedi`, but it might be less known...

**Comment by ckrey** [comment]
`Toot`?

**Comment by ckrey** [comment]
`Toot`, `Read`, `Talk`, `Git...`, `Donate`

**Comment by jpmens** [comment]
`s/Git../Code/` ?

**Comment by jpmens** [comment]
Toot is good

**Comment by jpmens** [comment]
`Cash` would be good for Donate but maybe a bit hardcore. ;-)

How about `Good` ?

**Comment by ckrey** [comment]
I think all verbs would be good.

`Toot Read Talk Code Give`

But you are the native speaker

**Comment by jpmens** [comment]
Ship it!

**Comment by jpmens** [comment]
![rabbit-11567](https://github.com/user-attachments/assets/76101f32-7c91-4af4-92c0-fad22e9acb43)

I like the result. Thank you.
