### ISSUE TITLE
openHAB mqttitude binding reliability

### ISSUE THREAD

**Issue by mstormi** [owntracks/owntracks#4]
Hi,

I'm using the mqttitude binding of openHAB together with owntracks, and while I really love owntracks and highly appreciate all the efforts you put into it, I'm sorry to say that I found this combo to be unreliable in terms of presence detection and would like you to improve on that.

Now unreliability is probably not result of just a single big bug, but rather the result of a number of different scenarios where the whole system does not work perfectly, each of which to consist of a series of events (radio loss, server connectivity loss,
timeout, etc.) that sometimes might, but quite often are hard to reproduce and even harder to pin down (in terms "it happens whenever I ....").
I'm fully that that's pretty tedious work, especially as you spend your spare time on it ...
Anyway. To repeat: I really appreciate your efforts.
That being said, let's try getting the system a little more foolproof. Here's my ideas on that:

One major finding seems to me that as soon as one 'enter' or 'leave' message gets lost, the presence status easily can get out of sync with reality.

First, I noticed that enter/leave transition messages aren't set to retain. If they should be set to retain, that may or may not be a problem of my mosquitto or binding configuration, it that case please get me a hint what to look after.
But if they don't persist on the broker 'dashboard', visible to any (re-)connecting client (the binding, in particular), I can think of a number of series of events that might lead to 'out of sync'. 

Second, we should give a little bit more thought to what happens when clients go offline, for example during the night...
if you turn your mobile back on in the morning, it reconnects, but I believe it doesn't send a transition messages as it still is inside the radius to the 'home' waypoint it used to be the day before.
Simply put, why not introduce _unsolicited_ 'I'm in region X' messages to include waypoints names, and catch them on the binding side. That would compensate for enter/leave messages getting lost for whatever reason.

Finally third, as only clients do know the definition of waypoints, openHAB does not know about the region. So while the binding can read retained 'location' messages from the broker, it cannot make use of them. Please consider adding the ability to the binding to define waypoints+radius on the server side (inside the items file definition).
Note as we then might have 'competing' waypoint definitions this might lead to problems, but the ability to define locations on the 'server' (openHAB) side would still be beneficial. Maybe add the ability, too, to also define a priority mechanism (to define whether mobile waypoints override server ones or vice versa).

best regards
Markus

**Comment by jpmens** [comment]
@sumnerboy12 as our _resident OpenHAB specialist_, can you comment on this?

**Comment by sumnerboy12** [comment]
Hi Markus,

I don't think the Owntrack app writers will be keen to _retain_ transition events. But I may be proven wrong? @jpmens? I am not sure how or why your broker would ever be missing these events however. If you are concerned about openHAB _losing_ the waypoint status after a restart then you can investigate one of the supported persistence bindings in order to save the state and restore on a restart. 

If your phone is not publishing waypoint events then that is probably an issue with the location APIs of iOS and Android rather than anything in the apps themselves. Not much we can do about that sorry.

The binding already supports server-side waypoint definitions. You can quite easily set up two item definitions, one for the enter/leave transition event publishes, and one for the server-side monitoring (based on location publishes directly). If you create these two items within a Group:OR (see openHAB docs) you will get presence notifications for either events on that Group item.

Or if you require more complex logic then a simple openHAB rule which monitors those two items and manually updates a virtual _I-am-home_ item using your own logic, should work as well.

Regards,
Ben

**Comment by mstormi** [comment]
Am 26.09.2015 um 23:41 schrieb Ben Jones:
>
> Hi Markus,
>
> I don't think the Owntrack app writers will be keen to /retain/ 
> transition events. But I may be proven wrong? @jpmens 
> <https://github.com/jpmens>? I am not sure how or why your broker 
> would ever be missing these events however. If you are concerned about 
> openHAB /losing/ the waypoint status after a restart then you can 
> investigate one of the supported persistence bindings in order to save 
> the state and restore on a restart.
>
Sure. openHAB or mosquitto restarts are possible causes of problems, but 
for sure not the main ones.
I do use persistence already, of course, still presence detection is 
unreliable.
The main problem cause is loss of network connectivity (intermittent 
when on the move, as well as longer phases like overnight network absence).
And that's where I think to retain transition messages would help. Does 
anybody see any bad side effect of retaining the last enter/leave ?
>
> If your phone is not publishing waypoint events then that is probably 
> an issue with the location APIs of iOS and Android rather than 
> anything in the apps themselves. Not much we can do about that sorry.
>
As I wasn't aware of server-side waypoints, I was referring to 
unsolicited transition messages (because only those would have been 
caught by the binding) ... now if
we can achieve the same with location messages, there might be 'enough' 
of them already.
Still I believe you can improve there: add the ability to send location 
at fixed, regular intervals (not sure if that's what 'move mode' already 
does as I'm on Android).

Remember that for smart home applications, reliability and timing are of 
critical importance. Doesn't make sense to turn on the 'welcome home' 
lighting scene when you're already in.
Not to even think about auto-disabling the alarm system on arrival.

> The binding already supports server-side waypoint definitions. You can 
> quite easily set up two item definitions, one for the enter/leave 
> transition event publishes, and one for the server-side monitoring 
> (based on location publishes directly). If you create these two items 
> within a Group:OR (see openHAB docs) you will get presence 
> notifications for either events on that Group item.
>
> Or if you require more complex logic then a simple openHAB rule which 
> monitors those two items and manually updates a virtual /I-am-home/ 
> item using your own logic, should work as well.
>
Ok, I wasn't aware of that ... then docs on the binding are confusing. 
They read as if old (server-side waypoint) and new (app-side region) 
definition are mutually exclusive.
Could you please update the Wiki page to show a full-scale example how 
to configure OH to combine server-side and app-side definition ? Yes, 
for the logic, a Group:OR should do here.
>
> Regards,
> Ben
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/owntracks/owntracks/issues/4#issuecomment-143498644>.
>
regards,
Markus

**Comment by mstormi** [comment]
Am 26.09.2015 um 23:41 schrieb Ben Jones:
>
> The binding already supports server-side waypoint definitions. You can 
> quite easily set up two item definitions, one for the enter/leave 
> transition event publishes, and one for the server-side monitoring 
> (based on location publishes directly). If you create these two items 
> within a Group:OR (see openHAB docs) you will get presence 
> notifications for either events on that Group item.
>
I remember I had even tried that, and failed. Together with the state of 
docs, that lead me to believe that it ain't supposed to work that way.

So given your reply, I tried again. But again, it doesn't seem to work 
for me.
I have:
pi@pi /usr/share/openhab/configurations $ grep mqtti openhab.cfg
mqttitude:home.lat=51.6898199
mqttitude:home.lon=8.6889056
mqttitude:home.geofence=50
mqttitude:hometest.lat=51.6898199
mqttitude:hometest.lon=8.6889056
mqttitude:hometest.geofence=50
#mqttitude:home.lat=
#mqttitude:home.lon=
#mqttitude:home.geofence=
mqttitude:geofence=50
pi@pi /usr/share/openhab/configurations $ egrep 'Markus.*GPS' 
items/home.items
Switch Phone_GPS_Markus_homemarkus "Markus zuhause (app) (GPS)" 
<phone>         (Praesenz,Test) { 
mqttitude="mosquitto:owntracks/markus/s5/event:homemarkus" }
Switch Phone_GPS_Markus_hometest "Markus zuhause (server,test) (GPS)"   
<phone>         (Praesenz,Test) { 
mqttitude="mosquitto:owntracks/markus/s5:hometest" }
Switch Phone_GPS_Markus_home "Markus zuhause (server) (GPS)" 
<phone>         (Praesenz,Test) { 
mqttitude="mosquitto:owntracks/markus/s5:home" }
pi@pi /usr/share/openhab/configurations $


App-side control works (on re-confirming the 'homemarkus' waypoint in 
owntracks, a transition message is being sent and the openHAB item is 
switched to ON).
But server-side does not. On manual location report from @home, I see it 
arrive on the broker:
Client mosqsub/21430-pi received PUBLISH (d0, q0, r0, m0, 
'owntracks/markus/s5', ... (107 bytes))
owntracks/markus/s5 
{"_type":"location","lat":51.689804,"lon":8.6888894,"tst":1443345266,"acc":25,"batt":96,"t":"u","tid":"ms"}

... but *nothing* appears in the binding's log.
(in case 'home' is a received keyword, I also tried another name, but to 
no avail either)

Any idea?


Markus

**Comment by sumnerboy12** [comment]
As stated in the openHAB WIKI, in manual mode the binding will calculate your position `relative to a single fixed 'home' geofence`. So yes, `home` is a keyword.

Also in the WIKI it states the item binding config for a manual item is `mqttitude="<broker_id>:<mqtt_topic>"`. So no region/home key word after the topic.

Try that and see if you have any luck.

**Comment by mstormi** [comment]
Am 27.09.2015 um 11:44 schrieb Ben Jones:
>
> As stated in the openHAB WIKI, in manual mode the binding will 
> calculate your position |relative to a single fixed 'home' geofence|. 
> So yes, |home| is a keyword.
>
> Also in the WIKI it states the item binding config for a manual item 
> is |mqttitude="<broker_id>:<mqtt_topic>"|. So no region/home key word 
> after the topic.
>
> Try that and see if you have any luck.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/owntracks/owntracks/issues/4#issuecomment-143533459>.
>
Ok, with your hints, 'home' via location is working now - thanks!

But that means 'home' is the only waypoint that I can define on server 
side, right?
So while it of course is the most important one, I can't define any 
'work' or 'school'.
So if enter/leave messages at work or school get lost, I can still run 
out of sync.
(same background as @'home': bad in-building GPS and radio coverage, and 
you want to or have to switch off your phone for a longer period there).

So there's no e.g. 'turn on heating in X's room when X leaves 
work/school' (reliably) possible.

Would you be willing to add multiple (user-defineably named) server-side 
waypoints as a feature ?

best regards
Markus

**Comment by jpmens** [comment]
A couple of points regarding your first message.

1. Enter/leave transition messages don't simply _get lost_. Our apps publish MQTT messages with QoS=2 to avoid that precisely, in other words, we do our best to get that message to your broker (and its subscribing clients). 
2. Enter/leave transition messages are not retained and probably shouldn't be. If your device goes off at night and wakes up somewhere else, it ought to publish an "enter Elsewhere" transition.

**Comment by mstormi** [comment]
Am 27.09.2015 um 12:26 schrieb JP Mens:
>
> A couple of points regarding your first message.
>
>  1. Enter/leave transition messages don't simply /get lost/. Our apps
>     publish MQTT messages with QoS=2 to avoid that precisely, in other
>     words, we do our best to get that message to your broker (and its
>     subscribing clients).
>
Sure. I didn't mean to say that. But whenever there's enough network, 
device or server caused outages along the message chain, the server's 
knowledge can get out of sync with the mobile's whereabouts.
Right now, I've got two presence display items in my OH GUI based on 
owntracks region and server side 'home', and it's pretty weird to see 
them not show the same status.
It's showing something's inherently wrong, and having to take (smarthome 
or whatever) actions based on an uncertain state does feel even worse.
>
>  1. Enter/leave transition messages are not retained and probably
>     shouldn't be. If your device goes off at night and wakes up
>     somewhere else, it ought to publish an "enter Elsewhere" transition.
>
Do you mean owtracks *is* already publishing a transition message or 
startup/re-gaining network coverage/... ? Or did you mean to say it 
*should* do that (... in the future ...) ?
If the latter, then to publish a "enter Elsewhere" transition takes 
until you enter another waypoint.
It can take a long time until you reach your next waypoint, and 
meanwhile your status is unknown to the server. That state can last a 
long time. That's what's driving me.
On a sidenote: can owntracks handle overlapping waypoint/radius combos? 
Would it work to define a 'world' waypoint with a 40k km radius, then, 
to enforce the 'enter elsewhere' transition message?
On another sidenote: Ben @sumnerboy12, does the mqttitude binding 
properly cover LWT messages ? What does it do in case a client drops off 
the network, does it set the OH item to 'Uninitialized'
or will it retain its last state ?

Finally, why not retain transition messages ? The information that 
someone transitioned and when isn't inherently nonsense or even harmful, 
is it?
It's up to any server entity what to make of it (here: the mqttitude 
binding could use that information for sake of better status tracking, 
while owntracks app can ignore it).
You could at least allow for a user-configurable 'retain' flag on 
transition msgs (i.e. just apply the existing message config option to 
transition messages, too).
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/owntracks/owntracks/issues/4#issuecomment-143540238>.
>
regards
Markus

**Comment by sumnerboy12** [comment]
If a client loses connection to the broker, i.e. LWT, I don't believe this should have any effect on presence switches. If you wanted to handle this you can, but creating a simple MQTT item binding in openHAB subscribing to the LWT topic, and take the appropriate action in a rule.

As for your request for multiple server-side region support, I am afraid I won't be able to oblige. The next stage for the Mqttitude binding is to port it over to openHAB v2.0 and rename it to Owntracks. To be honest I was considering dropping the legacy server-side waypoint stuff, since the new event transitions work so much better.

I have found the waypoint events are fired very consistently, whereas with the way location pubs work, i.e. only pub if moved more than xxx metres since last pub, sometimes means if you get a location pub just before you enter your home region, and then stop moving once you get home, no further location pub is triggered since you haven't moved enough.

**Comment by mstormi** [comment]
Hmm. Ben, I sort of agree to your reasoning and it would be ok IF presence detection based on owntracks app-side messages DID work reliably, but it does not as of today.

**Comment by mstormi** [comment]
sorry, I didn't mean to close this issue. Not sure why it happened, maybe haven't had enough coffee yet this morning to identify the correct button.

**Comment by NCO3** [comment]
All,
I also encountered Markus' problems and I would personally prefer to setup server side regions instead of regions on the client. Especially with multiple clients it's much easier to maintain.
I currently reset the enter/leave switches manually, whenever I get an update on any of the regions.
This does solve the missed "leave" messages, but not the missed "enter" messages:
rule "Location Home"
when
	Item Loc_Home changed from OFF to ON
then
	postUpdate(Loc_BSL, OFF)
	postUpdate(Loc_City, OFF)
	postUpdate(Loc_Kita, OFF)
	postUpdate(Ort, "zuhause")
end

**Comment by sumnerboy12** [comment]
As mentioned, doing waypoint checks using location pubs only is far less effective than using the device OS waypoint-transition events. It is quite easy to get a location pub just before moving inside a waypoint, and then once you stop moving (i.e. at home) you won't get another location pub, which in turn means no region *enter* event.

There are ways to maintain config in JSON files which can be emailed/uploaded to devices for easier configuration if you have many devices with many waypoints. Typically most people have 3-4 devices and a couple of waypoints of interest however, so it is not a big deal.

**Comment by mstormi** [comment]
The point isn't about server or app-side tracking.
@sumnerboy12 is right, app-side tracking has advantages, and the extra 
effort to configure multiple devices is not that high.
But @NCO3 is right, too: the real point is that current app-side 
implementation isn't reliable enough yet.
See my proposals above how you could improve here (retain transition 
messages and send unsolicited 'in-area' messages).
@jpmens: have you given these some thoughts ?

Am 11.11.2015 um 20:46 schrieb Ben Jones:

**Comment by jpmens** [comment]
We won't be publishing transition messages retailed because the current "user is entering/leaving location" works with received transition messages.

We're not really understanding the point of resending events when a device reconnects: if your device was "at home" when it disconnected and reconnects in the morning at home, you haven't left so no transition event is required.

**Comment by mstormi** [comment]
> We won't be publishing transition messages retailed because the 
> current "user is entering/leaving location" works with received 
> transition messages.
>
> We're not really understanding the point of resending events when a 
> device reconnects: if your device was "at home" when it disconnected 
> and reconnects in the morning at home, you haven't left so no 
> transition event is required.
>
Hmm, and if I move outside my home waypoint before my phone reconnects 
or obtains a GPS signal ? I'll be out of sync until I enter another 
waypoint.
Anyway, my point isn't this specific problem case and when exactly or 
how likely it is to happen ... my point is rather that the overall 
systems's (= server plus clients) 'state machine' does not cover all 
possible series of events to ensure server status is always in sync with 
mobile client's. Use schemes are dependent on a user's habits, so 
running out of sync happens to some people more often than to others, 
but in sum, I think it's not unfair to claim that region detection does 
not work reliably yet.
And I believe you won't ever get the state machine completely correct in 
an algorithmic sense. No blaming or pun intended here .... there will 
always be situations where triggers (e.g. GPS) or messages don't arrive 
or arrive too late.
So instead of putting efforts into 'debugging' all sorts of problem 
cases from the algorithmic point of view, I believe overall, it's better 
to improve status tracking  by sending unsolicited (or from your point 
of view: unnecessary) messages.
They don't do real harm, but they will compensate for most state machine 
'failures'.
That's why I suggested the 'resend-on-reconnect', but even more so, the 
ability to send a 'in-area-X' status message at regular, user-definable 
intervals.
In the end, that's what you already do with location messages, probably 
for good reasons. But given that area definition is client-side, any 
status tracking server like openHAB relies on the 'in-area-X'  
information to be
transmitted just as much as owntracks relies on regular location 
updates. Or actually even more so, because in a openHAB/smarthome 
context, timing is more critical than it is for owntracks' standard 
'display whereabouts' use case.
Maybe - just a spontaneous idea - long time, this could even be 
'externalized', i.e.have owntracks offer some kind of interface and use 
something external like IFTTT or similar automation app to trigger 
location and in-area-X updates,
so we can update on virtually any kind of trigger, too, like WLAN or 
Bluetooth connects.
But I'd be more than happy if you did implement the 'in-area-X' at 
regular intervals  (and if you add the ability to customize the interval 
down to a couple of seconds, we also wouldn't need resend-on-reconnect).

best regards
Markus

**Comment by binarybucks** [comment]
> Hmm, and if I move outside my home waypoint before my phone reconnects
or obtains a GPS signal ? I'll be out of sync until I enter another
waypoint.

If we were to send event messages on connect, the last known event to the device would be "entering home" in that case. Sending this on connect would make things even worse, wouldn't it?

> In the end, that's what you already do with location messages, probably
for good reasons.
No, we send location messages when we get a callback from the location APIs that something changed. We do not periodically publish the last known location even if it didn't change.

I don't really really get the point to be honest. Your problem is, that the device might miss a transition for whatever reason (GPS problems, location API problems, device Off, solar flare). And you are right that it doesn't make sense to debug this because of the large number of possible reasons. 

But so is the situation on the device itself. Broadcasting the last known states might help a bit, but it doesn't help against the very frequent issue where the phone's location API just doesn't give us updates for whatever reason. In that case you will get an old location that is likely wrong and no matter how often we publish the last known location, it will be wrong until the location API gives us an update in which case a new location emssage will be send anyway.

**Comment by mstormi** [comment]
>     Hmm, and if I move outside my home waypoint before my phone reconnects
>     or obtains a GPS signal ? I'll be out of sync until I enter another
>     waypoint.
>
> If we were to send event messages on connect, the last known event to 
> the device would be "entering home" in that case. Sending this on 
> connect would make things even worse, wouldn't it?
>
>     In the end, that's what you already do with location messages,
>     probably
>     for good reasons.
>     No, we send location messages when we get a callback from the
>     location APIs that something changed. We do not periodically
>     publish the last known location even if it didn't change.
>
Oh. Then unlike I thought, the core 'display whereabouts service' 
already suffers from the same type of problem causes that I was thinking 
to address. So improving there might already help with my status 
tracking problems, too.

How about complementing the current 'passive' mode of operation with an 
'active' one, then ? I.e. don't (only) wait for callback, but in 
parallel, do actively query GPS (some API, in the end) at regular 
intervals and publish the location result.
If owntracks didn't miss updates from the API, then it re-publishes 
unchanged information, but that doesn't really make things worse, does 
it? On the other hand, the active query *might* yield a new result.
If you make that mode optional and allow for a user-definable interval 
(off = how owntracks works today), anyone afraid of battery drain or 
unconvinced of the concept :-) can increase the interval or disable it.
By the way, isn't that what 'move mode' is supposed to do in iOS? (to 
avoid misunderstandings: I have never used or investigated it any closer 
because I'm on Android only).

> I don't really really get the point to be honest. Your problem is, 
> that the device might miss a transition for whatever reason (GPS 
> problems, location API problems, device Off, solar flare). And you are 
> right that it doesn't make sense to debug this because of the large 
> number of possible reasons.
>
> But so is the situation on the device itself. Broadcasting the last 
> known states might help a bit, but it doesn't help against the very 
> frequent issue where the phone's location API just doesn't give us 
> updates for whatever reason. In that case you will get an old location 
> that is likely wrong and no matter how often we publish the last known 
> location, it will be wrong until the location API gives us an update 
> in which case a new location emssage will be send anyway.
>
I agree the API to not call back (just sometimes and for whatever 
reason) is the by far bigger issue. To possibly compensate for that, see 
proposal above. Still, as you say for yourself: broadcasting can help in 
a (minor, but non-zero) number of situations.
And it doesn't do harm either because both, the current working mode (no 
action) as well as the alternative mode (to (re-)broadcast potentially 
outdated information) do result in the same: no update of the user's 
location on the display or his status (area presence).

**Comment by binarybucks** [comment]
On Android it's not that Owntracks "misses" updates from the API but that the API misses location changes. Thus you can set the background location accuracy to high and displacement and interval to something low which makes it more likely to wake up and get updates by GPS fixes (and burn a good amount of battery). 

For Android it's very simple. 
There is a location API that provides geofences. 
You can tweak it a bit by changing the background accuracy, displacement and interval. 
If the device automagically detects a geofence transition, Owntracks gets a callback and publishes the transition. 
If the device misses a transition because of $REASON, Owntracks doesn't get a  callback and doesn't publish a tranisition. 
If the device detects a location change, Owntracks gets a callback and publishes a location message. 
If it doesn't detect a location change, it doesn't publish a location message. 

No matter how many additional messages you create around that basic behaviour, you won't get any new information out of it because the device simply doesn't know any new information.

Location tracking based on data provided by mobiles has it's limits because these devices do all they can to preserve power and that's a good thing. Block level tracking is pretty reliable and good to record general movement.  House level tracking mostly reliable by pulling in a variety (mostly WiFi networks) of other information but more accurate and instant tracking is prevented by deep sleep modes of the devices. 

If you need higher precision, phones are the wrong tool for the job. Get a cheap BLE key fob and detect it's presence or use OwnTracks to detect BLE beacons that are in range to send a publish because that's what the protocol was designed for.

**Comment by mstormi** [comment]
Am 13.11.2015 um 10:59 schrieb Alexander Rust:
>
> On Android it's not that Owntracks "misses" updates from the API but 
> that the API misses location changes. Thus you can set the background 
> location accuracy to high and displacement and interval to something 
> low which makes it more likely to wake up and get updates by GPS fixes 
> (and burn a good amount of battery).
>
> For Android it's very simple.
> There is a location API that provides geofences.
> You can tweak it a bit by changing the background accuracy, 
> displacement and interval.
> If the device automagically detects a geofence transition, Owntracks 
> gets a callback and publishes the transition.
> If the device misses a transition because of $REASON, Owntracks 
> doesn't get a callback and doesn't publish a tranisition.
> If the device detects a location change, Owntracks gets a callback and 
> publishes a location message.
> If it doesn't detect a location change, it doesn't publish a location 
> message.
>
> No matter how many additional messages you create around that basic 
> behaviour, you won't get any new information out of it because the 
> device simply doesn't know any new information.
>

Ok, that's how it currently works. I do already use high accuracy und 
rather small intervals, still it runs out of sync too often.
Of course your mileage may vary, but if I understand you correctly, you 
also feel it's failing too often, right?
So what about my proposals - can't you *actively* query GPS without 
using the same API that is supposed to call back (but doesn't always do 
so :-)) ?
And status broadcasts would be an improvement, too - while the location 
and especially the information which area I'm currently in may not be 
new to the device, it might be new to the server (if previous 
transmissions failed because of $REASON).
Or what's your idea how to improve?
>
> Location tracking based on data provided by mobiles has it's limits 
> because these devices do all they can to preserve power and that's a 
> good thing. Block level tracking is pretty reliable and good to record 
> general movement. House level tracking mostly reliable by pulling in a 
> variety (mostly WiFi networks) of other information but more accurate 
> and instant tracking is prevented by deep sleep modes of the devices.
>
> If you need higher precision, phones are the wrong tool for the job. 
> Get a cheap BLE key fob and detect it's presence or use OwnTracks to 
> detect BLE beacons that are in range to send a publish because that's 
> what the protocol was designed for.
>
True, but we're talking about somewhat different things. I'm looking for 
better tracking, but it's not about timing or high precision. These are 
somewhat related, but first and foremost, It's about *reliability*.
It's about use cases like 'turn on my heating when I leave work' or 
'turn on outside lights or open the garage door before arrival'. I don't 
mind it to take a minute
longer or less as long as I reliably do receive the message (ok, 
preferrably with a fixed timing offset) .
A BLE beacon or WLAN signal detector will trigger no sooner than when 
I've already reached the door - that's too late for these use cases (and 
many more to come).
Or think of all safety related actions where reliability is a must (say, 
to trigger an alarm when there's movement in your house, but your phone 
indicates you're at work).
No, phones quite *are* the right tool for this kind of job. The only 
ones, actually (that's why I'm so eager to get this to work well).

**Comment by pallemannen** [comment]
Sorry for resurrecting this old thread, but I have the same problem. I get location messages just fine, but transmission messages are intermittent - more often not sent than sent.

One easy solution (if the API allows it) would be to always have the location messages also include all regions you are inside of. Pseudo:

{"_type":"location","acc":42,"batt":48,"lat":37.7074469,"lon":-121.8891729,"tid":"y7","tst":1470689884,"regions":["Home", "HomeCity"]}

{"_type":"location","acc":42,"batt":48,"lat":37.7074469,"lon":-121.8891729,"tid":"y7","tst":1470689884,"regions":["Work", "Dublin", "California"]}

Even if you skip the array thingy and only include one region, it would make things easier to deal with server side:

{"_type":"location","acc":42,"batt":48,"lat":37.7074469,"lon":-121.8891729,"tid":"y7","tst":1470689884,"region":"Home"}

mstormi: How did you ultimately solve the problem (if you did)? I will probably skip the transition messages, and only listen to the location messages - and then use OpenHAB rules to calculate distanceFrom for all my regions (home, work, etc) - and then have the rules set the presence switches. I.e. not using the geofences of the app, and neither the ones of the binding, but rather coding my own:

rule "MQTT Owntracks Patrik"
  when 
    Item mqtt_owntracks_palaxy7 changed
  then
    var String json = (mqtt_owntracks_palaxy7.state as StringType).toString
    var String type = transform("JSONPATH", "$._type", json)
    if (type == "location") {
      var String lat  = transform("JSONPATH", "$.lat", json)
      var String lon  = transform("JSONPATH", "$.lon", json)
      var String batt = transform("JSONPATH", "$.batt", json)
      mqtt_owntracks_palaxy7_latitude.postUpdate(lat)
      mqtt_owntracks_palaxy7_longitude.postUpdate(lon)
      mqtt_owntracks_palaxy7_battery.postUpdate(batt)
      mqtt_owntracks_palaxy7_latlong.postUpdate(lat + ", " + lon)
      var PointType home = new PointType("37.697435,-121.866048")
      var PointType work = new PointType("37.707447,-121.889173")
      var PointType phone = new PointType(lat + "," + lon)
      val BigDecimal distHome = phone.distanceFrom(home).toBigDecimal
      val BigDecimal distWork = phone.distanceFrom(home).toBigDecimal
      var String loc = String::format("%1$.0f", distHome) + " m from home"
      if (distHome < 100) {
        loc = "at home"
      } else if (distWork < 100) {
      	loc = "at home"
      }
      mqtt_owntracks_palaxy7_location.postUpdate(phone)
      mqtt_owntracks_palaxy7_distancefromhome.postUpdate(phone.distanceFrom(home))
      mqtt_owntracks_palaxy7_latlongdist.postUpdate(lat + ", " + lon + " (" + loc + ")")
    }
end

It's a bit more cumbersome, but it's more reliable.

Regards
/P

**Comment by mstormi** [comment]
Using current owntracks and the recently introduced gpstracker binding of openHAB, transition recognition seems to work reasonably.
So I'll close this one and reopen in case of new problems to show up.
