### ISSUE TITLE
login credentials hidden by keyboard on iPhone4

### ISSUE THREAD

**Issue by tiptronic** [owntracks/owntracks#6]
When trying to log into an existing hosted account, there's no way to enter the credentials on an iPhone4, because the keyboard overlaps the text-fields and the view-controller doesn't accomodate for this.

If I tap into one of the fields (e.g. token) before the keyboards shows, and then hit RETURN, the view moves 50% down alltogether and the only chance to quit is to force-quit the app. (similar on iPhone5)

**Comment by ckrey** [comment]
closed here, will be followed up in owntracks/ios
